# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rdzhao/Documents/MS_Intersection

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rdzhao/Documents/MS_Intersection

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rdzhao/Documents/MS_Intersection/CMakeFiles /home/rdzhao/Documents/MS_Intersection/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rdzhao/Documents/MS_Intersection/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MS_Intersection

# Build rule for target.
MS_Intersection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MS_Intersection
.PHONY : MS_Intersection

# fast build rule for target.
MS_Intersection/fast:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/build
.PHONY : MS_Intersection/fast

Atom_sphere.o: Atom_sphere.cpp.o
.PHONY : Atom_sphere.o

# target to build an object file
Atom_sphere.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Atom_sphere.cpp.o
.PHONY : Atom_sphere.cpp.o

Atom_sphere.i: Atom_sphere.cpp.i
.PHONY : Atom_sphere.i

# target to preprocess a source file
Atom_sphere.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Atom_sphere.cpp.i
.PHONY : Atom_sphere.cpp.i

Atom_sphere.s: Atom_sphere.cpp.s
.PHONY : Atom_sphere.s

# target to generate assembly for a file
Atom_sphere.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Atom_sphere.cpp.s
.PHONY : Atom_sphere.cpp.s

Jenkins_Traub.o: Jenkins_Traub.cpp.o
.PHONY : Jenkins_Traub.o

# target to build an object file
Jenkins_Traub.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Jenkins_Traub.cpp.o
.PHONY : Jenkins_Traub.cpp.o

Jenkins_Traub.i: Jenkins_Traub.cpp.i
.PHONY : Jenkins_Traub.i

# target to preprocess a source file
Jenkins_Traub.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Jenkins_Traub.cpp.i
.PHONY : Jenkins_Traub.cpp.i

Jenkins_Traub.s: Jenkins_Traub.cpp.s
.PHONY : Jenkins_Traub.s

# target to generate assembly for a file
Jenkins_Traub.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Jenkins_Traub.cpp.s
.PHONY : Jenkins_Traub.cpp.s

Matrix44.o: Matrix44.cpp.o
.PHONY : Matrix44.o

# target to build an object file
Matrix44.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Matrix44.cpp.o
.PHONY : Matrix44.cpp.o

Matrix44.i: Matrix44.cpp.i
.PHONY : Matrix44.i

# target to preprocess a source file
Matrix44.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Matrix44.cpp.i
.PHONY : Matrix44.cpp.i

Matrix44.s: Matrix44.cpp.s
.PHONY : Matrix44.s

# target to generate assembly for a file
Matrix44.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Matrix44.cpp.s
.PHONY : Matrix44.cpp.s

Torus.o: Torus.cpp.o
.PHONY : Torus.o

# target to build an object file
Torus.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Torus.cpp.o
.PHONY : Torus.cpp.o

Torus.i: Torus.cpp.i
.PHONY : Torus.i

# target to preprocess a source file
Torus.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Torus.cpp.i
.PHONY : Torus.cpp.i

Torus.s: Torus.cpp.s
.PHONY : Torus.s

# target to generate assembly for a file
Torus.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Torus.cpp.s
.PHONY : Torus.cpp.s

Vector2d.o: Vector2d.cpp.o
.PHONY : Vector2d.o

# target to build an object file
Vector2d.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Vector2d.cpp.o
.PHONY : Vector2d.cpp.o

Vector2d.i: Vector2d.cpp.i
.PHONY : Vector2d.i

# target to preprocess a source file
Vector2d.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Vector2d.cpp.i
.PHONY : Vector2d.cpp.i

Vector2d.s: Vector2d.cpp.s
.PHONY : Vector2d.s

# target to generate assembly for a file
Vector2d.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Vector2d.cpp.s
.PHONY : Vector2d.cpp.s

Vector3d.o: Vector3d.cpp.o
.PHONY : Vector3d.o

# target to build an object file
Vector3d.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Vector3d.cpp.o
.PHONY : Vector3d.cpp.o

Vector3d.i: Vector3d.cpp.i
.PHONY : Vector3d.i

# target to preprocess a source file
Vector3d.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Vector3d.cpp.i
.PHONY : Vector3d.cpp.i

Vector3d.s: Vector3d.cpp.s
.PHONY : Vector3d.s

# target to generate assembly for a file
Vector3d.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/Vector3d.cpp.s
.PHONY : Vector3d.cpp.s

concave_edge.o: concave_edge.cpp.o
.PHONY : concave_edge.o

# target to build an object file
concave_edge.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/concave_edge.cpp.o
.PHONY : concave_edge.cpp.o

concave_edge.i: concave_edge.cpp.i
.PHONY : concave_edge.i

# target to preprocess a source file
concave_edge.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/concave_edge.cpp.i
.PHONY : concave_edge.cpp.i

concave_edge.s: concave_edge.cpp.s
.PHONY : concave_edge.s

# target to generate assembly for a file
concave_edge.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/concave_edge.cpp.s
.PHONY : concave_edge.cpp.s

concave_sphere.o: concave_sphere.cpp.o
.PHONY : concave_sphere.o

# target to build an object file
concave_sphere.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/concave_sphere.cpp.o
.PHONY : concave_sphere.cpp.o

concave_sphere.i: concave_sphere.cpp.i
.PHONY : concave_sphere.i

# target to preprocess a source file
concave_sphere.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/concave_sphere.cpp.i
.PHONY : concave_sphere.cpp.i

concave_sphere.s: concave_sphere.cpp.s
.PHONY : concave_sphere.s

# target to generate assembly for a file
concave_sphere.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/concave_sphere.cpp.s
.PHONY : concave_sphere.cpp.s

convex_edge.o: convex_edge.cpp.o
.PHONY : convex_edge.o

# target to build an object file
convex_edge.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/convex_edge.cpp.o
.PHONY : convex_edge.cpp.o

convex_edge.i: convex_edge.cpp.i
.PHONY : convex_edge.i

# target to preprocess a source file
convex_edge.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/convex_edge.cpp.i
.PHONY : convex_edge.cpp.i

convex_edge.s: convex_edge.cpp.s
.PHONY : convex_edge.s

# target to generate assembly for a file
convex_edge.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/convex_edge.cpp.s
.PHONY : convex_edge.cpp.s

convex_face.o: convex_face.cpp.o
.PHONY : convex_face.o

# target to build an object file
convex_face.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/convex_face.cpp.o
.PHONY : convex_face.cpp.o

convex_face.i: convex_face.cpp.i
.PHONY : convex_face.i

# target to preprocess a source file
convex_face.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/convex_face.cpp.i
.PHONY : convex_face.cpp.i

convex_face.s: convex_face.cpp.s
.PHONY : convex_face.s

# target to generate assembly for a file
convex_face.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/convex_face.cpp.s
.PHONY : convex_face.cpp.s

grid_edge.o: grid_edge.cpp.o
.PHONY : grid_edge.o

# target to build an object file
grid_edge.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/grid_edge.cpp.o
.PHONY : grid_edge.cpp.o

grid_edge.i: grid_edge.cpp.i
.PHONY : grid_edge.i

# target to preprocess a source file
grid_edge.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/grid_edge.cpp.i
.PHONY : grid_edge.cpp.i

grid_edge.s: grid_edge.cpp.s
.PHONY : grid_edge.s

# target to generate assembly for a file
grid_edge.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/grid_edge.cpp.s
.PHONY : grid_edge.cpp.s

grid_point.o: grid_point.cpp.o
.PHONY : grid_point.o

# target to build an object file
grid_point.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/grid_point.cpp.o
.PHONY : grid_point.cpp.o

grid_point.i: grid_point.cpp.i
.PHONY : grid_point.i

# target to preprocess a source file
grid_point.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/grid_point.cpp.i
.PHONY : grid_point.cpp.i

grid_point.s: grid_point.cpp.s
.PHONY : grid_point.s

# target to generate assembly for a file
grid_point.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/grid_point.cpp.s
.PHONY : grid_point.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/main.cpp.s
.PHONY : main.cpp.s

saddle_face.o: saddle_face.cpp.o
.PHONY : saddle_face.o

# target to build an object file
saddle_face.cpp.o:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/saddle_face.cpp.o
.PHONY : saddle_face.cpp.o

saddle_face.i: saddle_face.cpp.i
.PHONY : saddle_face.i

# target to preprocess a source file
saddle_face.cpp.i:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/saddle_face.cpp.i
.PHONY : saddle_face.cpp.i

saddle_face.s: saddle_face.cpp.s
.PHONY : saddle_face.s

# target to generate assembly for a file
saddle_face.cpp.s:
	$(MAKE) -f CMakeFiles/MS_Intersection.dir/build.make CMakeFiles/MS_Intersection.dir/saddle_face.cpp.s
.PHONY : saddle_face.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... MS_Intersection"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Atom_sphere.o"
	@echo "... Atom_sphere.i"
	@echo "... Atom_sphere.s"
	@echo "... Jenkins_Traub.o"
	@echo "... Jenkins_Traub.i"
	@echo "... Jenkins_Traub.s"
	@echo "... Matrix44.o"
	@echo "... Matrix44.i"
	@echo "... Matrix44.s"
	@echo "... Torus.o"
	@echo "... Torus.i"
	@echo "... Torus.s"
	@echo "... Vector2d.o"
	@echo "... Vector2d.i"
	@echo "... Vector2d.s"
	@echo "... Vector3d.o"
	@echo "... Vector3d.i"
	@echo "... Vector3d.s"
	@echo "... concave_edge.o"
	@echo "... concave_edge.i"
	@echo "... concave_edge.s"
	@echo "... concave_sphere.o"
	@echo "... concave_sphere.i"
	@echo "... concave_sphere.s"
	@echo "... convex_edge.o"
	@echo "... convex_edge.i"
	@echo "... convex_edge.s"
	@echo "... convex_face.o"
	@echo "... convex_face.i"
	@echo "... convex_face.s"
	@echo "... grid_edge.o"
	@echo "... grid_edge.i"
	@echo "... grid_edge.s"
	@echo "... grid_point.o"
	@echo "... grid_point.i"
	@echo "... grid_point.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... saddle_face.o"
	@echo "... saddle_face.i"
	@echo "... saddle_face.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

